import type { Metadata } from "next";

import "./globals.css";
import SideMenu from "@/components/SideMenu";
import TopMenu from "@/components/TopMenu";
import { Barlow_Semi_Condensed } from "next/font/google";
const barlow = Barlow_Semi_Condensed({ 
  subsets: ["latin"], 
  weight: ["400"]
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow.className}>
      <SideMenu/>
      <TopMenu/>
      {children}
      </body>
    </html>
  );
}
